var ConversationConstants = {
  RECEIVE_CONVERSATION: "RECEIVE_CONVERSATION",
  RECEIVE_ALL_CONVERSATIONS: "RECEIVE_ALL_CONVERSATIONS",
  RECEIVE_SEARCH_CONVERSATIONS: "RECEIVE_SEARCH_CONVERSATIONS",
  REMOVE_CONVERSATION: "REMOVE_CONVERSATION",
  RECEIVE_ERRORS: "RECEIVE_CONVERSATION_ERRORS"
};

module.exports = ConversationConstants;
