var UserConstants = {
  RECEIVE_CURRENT_USER: "RECEIVE_CURRENT_USER",
  RECEIVE_SEARCH_USERS: "RECEIVE_SEARCH_USERS",
  REMOVE_CURRENT_USER: "REMOVE_CURRENT_USER",
  RECEIVE_ERRORS: "RECEIVE_USER_ERRORS"
};

module.exports = UserConstants;
